version: "3.8"

services:
  neo4j:
    image: neo4j
    container_name: my_neo4j
    environment:
      - NEO4J_AUTH=neo4j/test12345
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - neo4j-net

  jupyter:
    image: umd_data605_template
    container_name: jupyter_data605
    environment:
      - NEO4J_URI=bolt://my_neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=test12345
    ports:
      - "8888:8888"
    volumes:
      - ../:/workspace
    working_dir: /workspace
    command: jupyter notebook --ip=0.0.0.0 --no-browser --allow-root --notebook-dir=/workspace
    depends_on:
      - neo4j
    networks:
      - neo4j-net

networks:
  neo4j-net: